branches:
  only:
    - master
os:
  - linux

language: node_js

dist: trusty

sudo: required

node_js: 6

before_install:
  - sudo add-apt-repository -y ppa:dhor/myway
  - sudo apt-get -qq update
  - sudo apt-get -y install graphicsmagick
  - sudo apt-get -y install imagemagick

install:
  - npm install

env:
 global:
   - GH_REF: github.com/wilon/wilon.github.io.git
   - OC_REF: git.oschina.net/wilon/static.git
   - IS_TRAVIS: git show | grep '<travis@travis-ci.org>'

script:
  # 设置git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote set-url origin https://${GH_TOKEN}@${GH_REF}
  - git checkout master
  # 更新文件，没有 '<travis@travis-ci.org>' 的提交才更新一些文件，避免无限update
  - npm start
  - ${IS_TRAVIS} || wget -P static/ https://packagecontrol.io/channel_v3.json
  - ${IS_TRAVIS} || wget -P static/ https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.exe
  - ${IS_TRAVIS} || wget -P static/ https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-64-bit.deb
  - ${IS_TRAVIS} || gulp sitemap
  # 提交到oschina
  - git clone --depth=50 --branch=master https://${OC_TOKEN}@${OC_REF} static-tmp
  - cd static-tmp
  - cp -rf ../static/* .
  - git add .
  - git commit -m "Travis CI Auto Update"
  - git push --force "https://${OC_TOKEN}@git.oschina.net/wilon/static.git"

after_script:
  # 提交
  - cd ..
  - git add .
  - git commit -m "Travis CI Auto Update" &
  - git push --force origin master

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - wilonx@163.com
    on_success: never
    on_failure: always
