branches:
  only:
    - master
os:
  - linux

language: node_js

dist: trusty

sudo: required

node_js: 6

before_install:
  - sudo add-apt-repository -y ppa:dhor/myway
  - sudo apt-get -qq update
  - sudo apt-get -y install graphicsmagick
  - sudo apt-get -y install imagemagick

install:
  - npm install

env:
 global:
   - GH_REF: github.com/wilon/wilon.github.io.git
   - OC_REF: git.oschina.net/wilon/static.git

script:
  # 设置git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote set-url origin https://${GH_TOKEN}@${GH_REF}
  - git remote add oschina https://wilon:${OC_PASSWD}@${OC_REF}
  - git checkout master
  # 更新文件，没有 '<travis@travis-ci.org>' 的提交才更新一些文件，避免无限update
  - npm start
  - git show | grep '<travis@travis-ci.org>' || wget -O static/channel_v3.json https://packagecontrol.io/channel_v3.json
  - git show | grep '<travis@travis-ci.org>' || wget -O static/lantern-installer.exe https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.exe
  - git show | grep '<travis@travis-ci.org>' || wget -O static/lantern-installer-64-bit.deb https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-64-bit.deb
  - git show | grep '<travis@travis-ci.org>' || gulp sitemap

after_script:
  # 提交
  - git add .
  - git commit -m "Travis CI Auto Update" &
  - git push --force origin master
  - git push --force oschina master

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - wilonx@163.com
    on_success: never
    on_failure: never
