branches:
  only:
    - master
os:
  - linux

language: node_js

dist: trusty

sudo: required

node_js: 6

before_install:
  - sudo add-apt-repository -y ppa:dhor/myway
  - sudo apt-get -qq update
  - sudo apt-get -y install graphicsmagick
  - sudo apt-get -y install imagemagick

install:
  - npm install

script:
  # 设置git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote set-url origin https://${GH_TOKEN}@${GH_REF}
  - git checkout master
  # 更新文件，没有 '<travis@travis-ci.org>' 的提交才更新一些文件，避免无限update
  - npm start
  - git show | grep '<travis@travis-ci.org>' || wget -O static/channel_v3.json https://packagecontrol.io/channel_v3.json
  - git show | grep '<travis@travis-ci.org>' || gulp sitemap
  # 提交
  - git add .
  - git commit -m "Travis CI Auto Update"
  - git push --force origin master

env:
 global:
   - GH_REF: github.com/wilon/wilon.github.io.git
   - OC_REF: git.oschina.net/wilon/static.git

after_script:
  - git clone --depth=50 --branch=master https://${OC_TOKEN}@${OC_REF} static-tmp
  - cd static-tmp
  - cp -rf ../static/* .
  - git add .
  - git commit -m "Travis CI Auto Update"
  - git push --force "https://${OC_TOKEN}@git.oschina.net/wilon/static.git"

cache:
  directories:
    - node_modules
